clothing:
  jacket: leather
  trousers: denim
  times: 10s

logConf:
  appName: admin-server
  level: -1
  debug: true
  logPath: ./log/admin-server.log
  maxSize: 128
  maxAge: 7
  maxBackups: 30
  compress: false